version: '3.7'
services:
  node:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/yarn.lock
      - /usr/src/app/.next
    ports:
      - '3000:3000'
 